name: lingshiwwx
on:
  workflow_dispatch:
  schedule:
    - cron: '31 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lingshiwwx
        env:
          sn28692: ${{ secrets.sn28692 }}
        run: |
          echo $sn28692 | jq -r .m01362 | /bin/bash
          echo $df40 | jq -r .dodp35580 | /bin/bash
          echo $mvvx20 | jq -r .mfgmw92 | /bin/bash
          echo $cxy00 | jq -r .yncxz4341 | /bin/bash
          echo $uh59065 | jq -r .ywt45 | /bin/bash
          echo $lg29166 | jq -r .obj0850 | /bin/bash
          echo $ta25954 | jq -r .bvmk7 | /bin/bash

